# CRE workflow settings for oracle workflow

staging-settings:
  user-workflow:
    workflow-name: "flowforge-oracle-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: ""

